### ISSUE TITLE
freezed

### ISSUE THREAD

**Issue by yugo-miyabe** [yugo-miyabe/FlutterTraining#48]
公式ドキュメント:https://pub.dev/packages/freezed

# immutableとmutable

インスタンスにはimmutableとmutableという考え方があります。
immutableは不変、mutableは可変という意味です。

例えば、Userというクラスがあり、nameとageというフィールドを持つとします。
一般的な(mutableな)クラスとして定義されていれば、User user = User(name:"kazutxt",age:32)でインスタンスを生成した後に、user.age=32で値を書き換えることができます。
言い換えると、Userの状態は可変で、常に書き換えることができます。

**Comment by yugo-miyabe** [comment]
下記のパッケージを追加

```
dependencies:
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed:
```
