### ISSUE TITLE
パッケージの利用方法

### ISSUE THREAD

**Issue by yugo-miyabe** [yugo-miyabe/FlutterTraining#9]
Flutterにはよく使う機能を再利用可能な独立したパッケージとして、配布する仕組みがあります。

Flutterは世界中で使われており、有志の人たちが日々高品質で便利な機能を提供しつづけてくれています。

公開されているパッケージは下記のサイトで検索できる
https://pub.dev/

# パッケージの利用方法

1. pubspec.ymlに依存関係を記載する

```
dependencies:
  flutter:
    sdk: flutter
  パッケージ名: バージョン # 追加する
```
